---
title: "lynall05"
output: html_document
---
## Contents
Effects of excluding participants with minor inflammatory disease on:
- cell counts (MDD vs. control)
- PCA of cell counts
- PLS analysis

```{r}
library(ggplot2)
library(dplyr)
library(reshape2)
library(here)
library(magrittr)
library(ggfortify)

options(scipen=5) 

load(file=paste(here::here("res/"),"Apollo_qm_combi.Rdata",sep=""))

mel_wilcox <- function(formula, data=NULL){
  require(coin)
  w2 <- coin::wilcox_test(formula,data=data, distribution="exact", conf.int=TRUE)
  out <- c()
  out$n <- length(w2@statistic@block)
  out$y <- table(w2@statistic@x)
  out$formula <- formula
  out$estimate <- confint(w2)$estimate
  out$effect.size <- statistic(w2) / sqrt ( out$n )
  out$p.value <- coin::pvalue(w2)
  return(out) 
}  

# abs names
choice_qset <- c("q_rbc","q_platelet","q_baso","q_eosin","q_neut","q_mono_class","q_mono_int","q_mono_nonclass","q_cd4","q_cd8","q_b","q_nkt","q_nk16","q_nk56")
labels_qset <- c(q_rbc="RBCs",q_platelet="Platelets",q_baso="Basophils",q_eosin="Eosinophils",q_neut="Neutrophils",q_mono_class="Mono (classical)",q_mono_int="Mono (int)",q_mono_nonclass="Mono (non-class)",q_cd4="CD4+ T",q_cd8="CD8+ T",q_b="B cells",q_nkt="NKT cells",q_nk16="CD16(hi) NK",q_nk56="CD56(hi) NK")

labels_qset_long <- labels_qset
labels_qset_long["q_mono_int"] <- "Intermediate\nmonocytes"
labels_qset_long["q_mono_class"] <- "Classical\nmonocytes"
labels_qset_long["q_mono_nonclass"] <- "Non-classical\nmonocytes"

labels_humor <- c(crp_macs="CRP",p_il_6_mean="Plasma IL-6")
```

Cell counts
```{r}
# Exclude inflammatory disorder (takes down to 238)
qm_combi %<>% filter(!lynall_inflamm_yn=="yes")

# Medians
library(qwraps2)
cont <- qm_combi %>% select(disorder, "crp_macs", "p_il_6_mean", choice_qset)
tx <- as.data.frame(t(cont %>% group_by(disorder) %>% summarise_all(function(x){median_iqr(x,digits=3, na_rm=TRUE, show_n="never")})))
tx %<>% .[-1,] 
tx$p <- as.numeric("")
tx$eff <- as.numeric("")

for (i in 2:ncol(cont)){
  df <- cont %>% select(disorder,i)
  colnames(df) <- c("x","y")
  out <- mel_wilcox(y~x,data=df)
  tx$p[i-1] <- out$p.value 
  tx$eff[i-1] <- out$effect.size
}

rownames(tx) <- c("CRP","IL-6",labels_qset)

tx$missing <- as.numeric("")
tx$missing <- t(cont %>% summarise_at(vars(-one_of(c("disorder"))),~sum(is.na(.x)))) 

tx$variable <- rownames(tx)
tx %<>% select(variable, everything())
tx

tx$p.adj <- p.adjust(tx$p,method="BH")

write.table(tx,file=paste(here::here("res/"),"apollo_table_choice_qset_continuous_INFLAMM_EXCLUDED.csv",sep=""),sep="\t", dec=".", quote=FALSE, row.names = FALSE)

```

PCA
```{r}

tmp <- qm_combi[,choice_qset]
colnames(tmp) <- labels_qset
pca.out <- prcomp(tmp,center=T,scale=T)
pca.out$rotation[,1:2] %<>% "*"(-1)
pca.out$x[,1:2] %<>% "*"(-1)

eigen <- data.frame(pca.out$rotation[,1:2])
colnames(eigen) = c("PC1","PC2")

eigen$count <- rownames(eigen)

desired_order <- rev(c("Neutrophils","Eosinophils","Basophils","Mono (non-class)","Mono (int)","Mono (classical)", "CD4+ T" ,"CD8+ T" ,"CD16(hi) NK","CD56(hi) NK","NKT cells","B cells" ,"RBCs","Platelets"))            
# Re-order the levels
eigen$count <- factor( as.character(eigen$count), levels=desired_order )
# Re-order the data.frame
eigen <- eigen[order(eigen$count),]

# Plot
ggplot(melt(eigen, value.name="Eigenvector"),aes(x=count,y=Eigenvector, fill=variable)) + geom_bar(stat="identity") + coord_flip() + scale_x_discrete(labels=labels_qset) + facet_grid(~variable, scales="free") + xlab("") + ylab("") + scale_fill_discrete(name = "Component") + guides(fill=FALSE) + theme_bw()
ggsave(file=paste(here::here("pics/"),"apollo_all_pca_pca1and2_INFLAMM_EXCLUDED.pdf",sep=""),width=4,height=3.5)

# Add to the dataframe
qm_combi$PC1 <- NULL 
qm_combi <- data.frame(cbind(qm_combi,pca.out$x))

ggplot(data=qm_combi,aes(x=disorder,y=PC1)) + geom_violin(aes(fill=disorder)) + geom_boxplot(outlier.shape=NA, notch=FALSE, width=0.2) + guides(fill=FALSE) + scale_fill_manual(values=c("light grey","dark blue")) 
ggsave(file=paste(here::here("pics/"),"apollo_pc1_vs_disorder_INFLAMM_EXCLUDED.pdf",sep=""),width=2,height=3)

(tmp <- mel_wilcox(PC1~disorder,data=qm_combi)) # Effect remains significant at p=0.02, with effect size similar (0.15) 

# Supplementary PCA figure
autoplot(pca.out, data=qm_combi, colour='disorder', label=FALSE, loadings=TRUE, loadings.label=TRUE, loadings.label.size=4, loadings.label.hjust=-0.1, loadings.label.repel=TRUE, frame = TRUE, frame.type="t", frame.colour = 'disorder') + scale_color_manual(values = c("dark grey","blue")) + theme_bw() + theme(legend.position = c(0.1,0.1),legend.background = element_rect(color = "black"), legend.title = element_blank()) + coord_equal() 
ggsave(filename = paste(here::here("pics/"),"apollo_all_pca_by_disorder_INFLAMM_EXCLU.pdf",sep=""), width=7,height=5)

```

Correlations between PC1 and HAMD (excluding participants with minor inflammatory conditions)
```{r}
yin <- c("ham_17_score","bdi_total_score","shaps_score_calc","chalder_fatigue_score","ctq_total_score","leq_z","s_anxiety_score","t_anxiety_score")
labels_yin <- c("Depression (HAM-D)","Depression (BDI)","Anhedonia (SHAPS)","Chalder fatigue","Childhood trauma (CTQ)","Recent stress (LEQ)", "Stait anxiety (STAI-S)","Trait anxiety (STAI-T)")
names(labels_yin) <- yin

forcor <- qm_combi[,c("PC1","crp_macs","p_il_6_mean",yin,"age_at_bloods","bmi_calculated")]
labels_cor <- c("PC1"="Cellular PC1","crp_macs"="CRP","p_il_6_mean"="IL-6",labels_yin,"age_at_bloods"="age","bmi_calculated"="BMI")
forcor %<>% plyr::rename(replace=labels_cor)

tmp <- Hmisc::rcorr(data.matrix(forcor), type="spearman")
dim(tmp$P)
# Adjust correlation p values (only interested in correlations with clinical variables i.e. the 1st 33 p values)
praw <- gdata::lowerTriangle(tmp$P)
padjust <- p.adjust(praw[1:33], method="BH")

tmp$Padj <- tmp$P
gdata::lowerTriangle(tmp$Padj)[1:33] <- padjust
gdata::upperTriangle(tmp$Padj) = gdata::lowerTriangle(tmp$Padj, byrow=TRUE)

# Stats
tmp$Padj["Depression (HAM-D)","Cellular PC1"] # p=0.002
tmp$r["Depression (HAM-D)","Cellular PC1"] # rho=0.23
```


```{r}

sessionInfo()

```

